image: ubuntu

stages:
  - gather

.setup: &setup
  before_script:
  # Create the SSH directory and give it the correct permissions.
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  #
  # SSH Configuration
  #
  # - Disable strict host key checking.
  # - Set specific identity (private key) file.
  #
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\tIdentityFile $SSH_PRIVATE_KEY\n\n" >~/.ssh/config
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - git config --global user.name "${GITLAB_USER_NAME}"

  # The private key is stored as a 'File' type CI/CD environment variable. Where is that file?
  - echo $SSH_PRIVATE_KEY
  - chmod 700 $SSH_PRIVATE_KEY

  # Clone repository.
  - git clone git@gitlab.com:${CI_PROJECT_PATH}.git
  - cd ${CI_PROJECT_NAME}

  # Checkout branch (creating new branch off master if necessary).
  # - git checkout master
  # - git checkout -B $DATA_BRANCH master
  # - git branch --set-upstream-to=origin/$DATA_BRANCH $DATA_BRANCH || true
  # - git pull || true

data-daily:
  stage: gather
  <<: *setup
  script:
  - mkdir -p data-raw
  - cd data-raw
  - wget -q https://www.gstatic.com/covid19/mobility/Region_Mobility_Report_CSVs.zip -O mobility-regional.zip
  - unzip -o mobility-regional.zip
  - rm mobility-regional.zip
  - ls
  # - git add .
  # - git commit -m "Gather data [mobility] $(date +'%Y-%m-%d %H:%M')"
  # - git push --set-upstream origin $DATA_BRANCH -o ci.skip
