on:
  schedule:
    - cron:  '30 0 * * *'
  push:
    branches:
      - master
    tags:
      -'*'

name: update

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          install.packages(c("here", "usethis", "devtools"))
        shell: Rscript {0}

      - name: Download data
        run: |
          mkdir -p data-raw
          cd data-raw
          wget -q https://www.gstatic.com/covid19/mobility/Region_Mobility_Report_CSVs.zip -O mobility-regional.zip
          unzip -o mobility-regional.zip
          rm mobility-regional.zip
          ls

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Test update"
