on:
  push:
    branches:
      - master
    tags:
      -'*'

name: update

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Install R dependencies
        run: |
          install.packages(c("here", "usethis", "devtools"))
        shell: Rscript {0}

      - name: Download data
        run: |
          mkdir -p data-raw/regional
          cd data-raw
          wget -q https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv -O mobility-global.csv

      - name: Build package
        run: |
          devtools::build()
        shell: Rscript {0}
